Repository Lokathor/beryllium, pull requests merged in 2019-06, with the labels that each got.

#40 More examples
  .travis.yml
  Cargo.toml
  README.md
  appveyor.yml
  examples/audio_queue_tone.rs
  examples/blank_window.rs
  examples/extern_crate_gl.rs
  examples/extern_crate_glium.rs
  src/lib.rs
  src/opengl.rs
  src/palette.rs
  src/pixel_format.rs
  src/surface.rs
Labels: coverage, enhancement, example

#56 Clippy everything in this crate
  .travis.yml
  appveyor.yml
  examples/extern_crate_gl.rs
  examples/extern_crate_glium.rs
  examples/surface_editing.rs
  tests/pixel_format_tests.rs
Labels: enhancement

#52 Add support for window events and GL context flags constants.
  src/event.rs
  src/lib.rs
  src/opengl.rs
Labels: enhancement

#77 Add set_title and title
  src/window.rs
Labels: enhancement, sola

#79 Store window in the context, allow the window to be upgraded into a c…
  examples/extern_crate_gl.rs
  examples/extern_crate_glium.rs
  examples/surface_editing.rs
  src/lib.rs
  src/opengl.rs
  src/renderer.rs
  src/texture.rs
  src/window.rs
Labels: enhancement, example
